# Generated by Django 5.1.4 on 2026-09-25 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RideType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable code used by the apps, e.g. car_standard, car_xl, car_premium, bike.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("car", "Car"), ("bike", "Bike")],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, max_length=120)),
                ("seats", models.PositiveSmallIntegerField(default=4)),
                (
                    "min_vehicle_year",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="e.g. Premium requires 2019+.", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["service", "sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        choices=[("car", "Car"), ("bike", "Bike")], max_length=4
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("city", models.CharField(default="Lagos", max_length=60)),
                ("min_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("max_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("min_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("max_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FareQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pickup_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pickup_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "stops",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"lat":..,"lng":..,"address":".."}]',
                    ),
                ),
                ("distance_m", models.PositiveIntegerField()),
                ("duration_s", models.PositiveIntegerField()),
                (
                    "gross_amount",
                    models.PositiveIntegerField(
                        help_text="Fare before discount (kobo)."
                    ),
                ),
                ("discount_amount", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.PositiveIntegerField(
                        help_text="What the customer pays (kobo)."
                    ),
                ),
                ("breakdown", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fare_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.promocode",
                    ),
                ),
                (
                    "ride_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricing.ridetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FareRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city", models.CharField(default="Lagos", max_length=60)),
                ("base_amount", models.PositiveIntegerField(help_text="kobo")),
                ("per_km_amount", models.PositiveIntegerField(help_text="kobo per km")),
                (
                    "per_min_amount",
                    models.PositiveIntegerField(help_text="kobo per minute"),
                ),
                ("minimum_amount", models.PositiveIntegerField(help_text="kobo")),
                (
                    "booking_fee_amount",
                    models.PositiveIntegerField(default=0, help_text="kobo"),
                ),
                (
                    "cancellation_fee_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="kobo, charged when the customer cancels after the grace period",
                    ),
                ),
                (
                    "cancellation_grace_seconds",
                    models.PositiveIntegerField(default=120),
                ),
                ("free_wait_seconds", models.PositiveIntegerField(default=300)),
                (
                    "wait_per_min_amount",
                    models.PositiveIntegerField(
                        default=0, help_text="kobo per minute after the free wait"
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=15,
                        help_text="Platform commission on the fare.",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "ride_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fare_rules",
                        to="pricing.ridetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("ride_type", "city"),
                        name="one_active_rule_per_city",
                    )
                ],
            },
        ),
    ]
