# Generated by Django 5.1.4 on 2026-09-25 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incentive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        choices=[("car", "Car"), ("bike", "Bike")], max_length=4
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=160)),
                ("target_trips", models.PositiveIntegerField()),
                ("reward_amount", models.PositiveIntegerField(help_text="kobo")),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("min_acceptance_rate", models.PositiveSmallIntegerField(default=80)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("ride", "Ride fare"),
                            ("tip", "Tip"),
                            ("cancellation_fee", "Cancellation fee"),
                            ("topup", "Wallet top-up"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("method", models.CharField(max_length=6)),
                ("amount", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("gateway_reference", models.CharField(blank=True, max_length=120)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(max_length=20)),
                ("last4", models.CharField(max_length=4)),
                ("exp_month", models.PositiveSmallIntegerField()),
                ("exp_year", models.PositiveSmallIntegerField()),
                ("gateway", models.CharField(default="dummy", max_length=20)),
                (
                    "gateway_token",
                    models.CharField(
                        help_text="Authorization/token from Paystack or similar.",
                        max_length=255,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveBigIntegerField()),
                ("fee_amount", models.PositiveIntegerField(default=0)),
                (
                    "method",
                    models.CharField(
                        choices=[("scheduled", "Weekly"), ("instant", "Instant")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("on_hold", "On hold"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("bank_name", models.CharField(max_length=80)),
                ("bank_account_number", models.CharField(max_length=20)),
                ("bank_account_name", models.CharField(max_length=120)),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="What the user sees, e.g. '10% off your next 2 rides'.",
                        max_length=160,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("flat", "Flat amount")],
                        max_length=7,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="Percent (e.g. 10) or flat kobo amount."
                    ),
                ),
                (
                    "max_discount_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cap for percent promos (kobo).",
                        null=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[("car", "Car"), ("bike", "Bike")],
                        help_text="Empty = cars and bikes.",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total redemptions allowed.", null=True
                    ),
                ),
                ("per_user_limit", models.PositiveIntegerField(default=1)),
                ("first_ride_only", models.BooleanField(default=False)),
                (
                    "budget_amount",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Stops when discounts reach this (kobo).",
                        null=True,
                    ),
                ),
                ("spent_amount", models.PositiveBigIntegerField(default=0)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discount_amount", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fare", "Trip fare"),
                            ("commission", "Platform commission"),
                            ("tip", "Tip"),
                            ("cash_collected", "Cash collected from customer"),
                            ("cancellation_fee", "Cancellation fee (your share)"),
                            ("incentive", "Incentive bonus"),
                            ("payout", "Payout to bank"),
                            ("payout_fee", "Instant payout fee"),
                            ("payout_reversal", "Failed payout returned"),
                            ("adjustment", "Adjustment by staff"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        help_text="Signed kobo. + owed to provider, - owed by provider."
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance_amount", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="NGN", max_length=3)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("topup", "Top-up"),
                            ("ride_payment", "Ride payment"),
                            ("tip", "Tip"),
                            ("refund", "Refund"),
                            ("credit", "Ride credit / referral"),
                            ("cancellation_fee", "Cancellation fee"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        help_text="Signed: + credit, - debit (kobo)."
                    ),
                ),
                ("balance_after", models.BigIntegerField()),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncentiveAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveIntegerField()),
                (
                    "incentive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="payments.incentive",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
