# Generated by Django 5.1.4 on 2026-09-25 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        choices=[("car", "Car"), ("bike", "Bike")],
                        db_index=True,
                        help_text="car = driver, bike = rider",
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("documents_pending", "Documents pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(default="Lagos", max_length=60)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_online", models.BooleanField(db_index=True, default=False)),
                (
                    "last_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "last_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "last_heading",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("last_location_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("total_trips", models.PositiveIntegerField(default=0)),
                ("offers_received", models.PositiveIntegerField(default=0)),
                ("offers_accepted", models.PositiveIntegerField(default=0)),
                ("trips_cancelled", models.PositiveIntegerField(default=0)),
                ("bank_name", models.CharField(blank=True, max_length=80)),
                ("bank_account_number", models.CharField(blank=True, max_length=20)),
                ("bank_account_name", models.CharField(blank=True, max_length=120)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("drivers_licence", "Driver's licence (cars)"),
                            ("riders_licence", "Rider's licence, class A (bikes)"),
                            ("insurance", "Insurance certificate"),
                            ("vehicle_registration", "Vehicle / bike registration"),
                            ("national_id", "National ID (NIN)"),
                            ("profile_photo", "Profile photo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="provider_documents/%Y/%m/")),
                (
                    "back_file",
                    models.FileField(
                        blank=True,
                        help_text="Back side, if any.",
                        null=True,
                        upload_to="provider_documents/%Y/%m/",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=60)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        help_text="Shown to the driver/rider in the app.",
                        max_length=255,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="providers.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("car", "Car"), ("bike", "Bike")],
                        help_text="car or bike (matches the provider's service)",
                        max_length=4,
                    ),
                ),
                ("make", models.CharField(max_length=40)),
                ("model", models.CharField(max_length=40)),
                ("year", models.PositiveSmallIntegerField()),
                ("color", models.CharField(max_length=30)),
                ("plate_number", models.CharField(max_length=15, unique=True)),
                ("seats", models.PositiveSmallIntegerField(default=4)),
                ("has_rider_helmet", models.BooleanField(default=False)),
                ("has_passenger_helmet", models.BooleanField(default=False)),
                ("has_reflective_vest", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending inspection"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="The vehicle currently being driven."
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "ride_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ride types this vehicle may serve (set on approval).",
                        to="pricing.ridetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
