# Generated by Django 5.1.4 on 2026-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="has_delivery_box",
            field=models.BooleanField(
                default=False, help_text="Top box or delivery bag for packages."
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="has_passenger_helmet",
            field=models.BooleanField(
                default=False, help_text="Old passenger-bike field. No longer required."
            ),
        ),
    ]
