# Generated by Django 5.1.4 on 2026-09-25 10:11

import apps.rides.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("pricing", "0001_initial"),
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        choices=[("car", "Car"), ("bike", "Bike")],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("searching", "Finding a driver/rider"),
                            ("accepted", "Driver/rider on the way"),
                            ("arrived", "Driver/rider at pickup"),
                            ("in_progress", "On trip"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_provider", "No driver/rider found"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("city", models.CharField(default="Lagos", max_length=60)),
                ("pickup_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pickup_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pickup_address", models.CharField(max_length=255)),
                (
                    "pickup_note",
                    models.CharField(
                        blank=True,
                        help_text="Landmark note for the driver, e.g. 'Blue gate, opposite GTBank'.",
                        max_length=255,
                    ),
                ),
                ("dropoff_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_address", models.CharField(max_length=255)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("distance_m", models.PositiveIntegerField(default=0)),
                ("duration_s", models.PositiveIntegerField(default=0)),
                (
                    "gross_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Fare before discount, incl. waiting charge.",
                    ),
                ),
                ("discount_amount", models.PositiveIntegerField(default=0)),
                ("wait_charge_amount", models.PositiveIntegerField(default=0)),
                ("total_amount", models.PositiveIntegerField(default=0)),
                ("tip_amount", models.PositiveIntegerField(default=0)),
                ("commission_amount", models.PositiveIntegerField(default=0)),
                ("cancellation_fee_amount", models.PositiveIntegerField(default=0)),
                ("refunded_amount", models.PositiveIntegerField(default=0)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("wallet", "Chicano wallet"),
                        ],
                        default="cash",
                        max_length=6,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("cash_collected_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("provider", "Driver/rider"),
                            ("staff", "Staff"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("helmet_handed_over_at", models.DateTimeField(blank=True, null=True)),
                ("helmet_returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "needs_manual_dispatch",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Shown in Super Admin > Dispatch.",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        default=apps.rides.models._share_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride",
                        to="pricing.farequote",
                    ),
                ),
                (
                    "ride_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricing.ridetype",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="providers.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("customer_to_provider", "Customer rates driver/rider"),
                            ("provider_to_customer", "Driver/rider rates customer"),
                        ],
                        max_length=24,
                    ),
                ),
                ("stars", models.PositiveSmallIntegerField()),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["Smooth driving", "Clean helmet"]',
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.CharField(max_length=40)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RideOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired (no answer)"),
                            ("withdrawn", "Withdrawn (ride cancelled/reassigned)"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("distance_to_pickup_m", models.PositiveIntegerField()),
                ("eta_to_pickup_s", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Assigned by staff from the Dispatch screen.",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RideStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.CharField(max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["status", "service"], name="rides_ride_status_af79ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(
                fields=["customer", "-created_at"], name="rides_ride_custome_dbf2cd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("ride", "direction"), name="one_rating_per_direction"
            ),
        ),
    ]
