# Generated by Django 5.1.4 on 2026-10-02 09:44

from django.db import migrations, models


def backfill_packages(apps, schema_editor):
    """Bike rides booked by older app builds have the package in pickup_note; copy it into the new fields."""
    from apps.rides.delivery import parse_delivery_note
    Ride = apps.get_model("rides", "Ride")
    for ride in Ride.objects.filter(service="bike", package_kind="", pickup_note__startswith="PACKAGE: ").iterator():
        p = parse_delivery_note(ride.pickup_note)
        if not p:
            continue
        ride.package_kind, ride.package_size = p["kind"][:20], p["size"][:10]
        ride.package_contents, ride.package_fragile = p["contents"][:120], p["fragile"]
        phone = p["recipient_phone"]
        try:
            from apps.accounts.services import normalize_phone
            phone = normalize_phone(phone)
        except Exception:
            pass
        ride.recipient_name, ride.recipient_phone = p["recipient_name"][:80], phone[:20]
        if ride.helmet_handed_over_at:
            ride.package_collected_at = ride.helmet_handed_over_at
        ride.save(update_fields=["package_kind", "package_size", "package_contents", "package_fragile",
                                 "recipient_name", "recipient_phone", "package_collected_at"])


def bike_ride_type_copy(apps, schema_editor):
    """The bike ride type said 'Helmet provided' (passenger copy). Bikes now carry packages."""
    RideType = apps.get_model("pricing", "RideType")
    RideType.objects.filter(service="bike", description__icontains="helmet").update(description="Fast package delivery across town")


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="package_collected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Rider confirmed the package at pickup.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="package_contents",
            field=models.CharField(
                blank=True,
                help_text="Optional: what exactly is inside.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="package_fragile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ride",
            name="package_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Documents", "Documents"),
                    ("Parcel", "Parcel"),
                    ("Food", "Food"),
                    ("Groceries", "Groceries"),
                    ("Electronics", "Electronics"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="package_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Small", "Small · fits in a bag"),
                    ("Medium", "Medium · shoebox"),
                    ("Large", "Large · delivery box, up to about 10 kg"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="ride",
            name="recipient_phone",
            field=models.CharField(
                blank=True, help_text="E.164, e.g. +2348034125567.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='e.g. ["Smooth driving", "Package arrived safe"]',
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_note",
            field=models.CharField(
                blank=True,
                help_text="Landmark note for the driver/rider, e.g. 'Blue gate, opposite GTBank'.",
                max_length=255,
            ),
        ),
        migrations.RunPython(backfill_packages, migrations.RunPython.noop),
        migrations.RunPython(bike_ride_type_copy, migrations.RunPython.noop),
    ]
